#cloud-config
version: 2

runcmd:
  - [ bash, -c, 'echo "Starting the dummy Flask app"' ]
  - [ bash, -c, 'cd /home/outscale/flask_app && source venv/bin/activate && python3 app.py --name "B"' ]
  - [ bash, -c, 'echo "App ready..."' ]

